<a href="https://colab.research.google.com/github/estateangela/PythonClass/blob/main/BI0515.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
n1d = np.array([1,2,3])
n1d , n1d.shape

(array([1, 2, 3]), (3,))

In [3]:
n1d[2] = 10
n1d

array([ 1,  2, 10])

In [4]:
n2d = np.array([[1,2,3],[14,125,16]])
n2d,n2d.shape

(array([[  1,   2,   3],
        [ 14, 125,  16]]),
 (2, 3))

In [5]:
'n2d[0][1]=',n2d[0][1],'n2d[0,1]=',n2d[0,1]

('n2d[0][1]=', 2, 'n2d[0,1]=', 2)

In [6]:
n2d[0,-1]

3

In [7]:
n2d[-1]

array([ 14, 125,  16])

In [10]:
n1d = [1,2,3,4,5,6,7,8,9]
n1d[2:-2] #頭包含尾不包含
n1d[2:-2:3]

[3, 6]

In [11]:
print(n1d[:-2])
print(n1d[1:])
print(n1d[1:len(n1d)])

[1, 2, 3, 4, 5, 6, 7]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
n2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
n2d, n2d.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 (4, 3))

In [17]:
n2d[3,1], n2d[1:3,1], n2d[0:3,0:2], n2d[1:3,1:2]

(11,
 array([5, 8]),
 array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[5],
        [8]]))

In [21]:
n2d[1,1:3],n2d[3,1:3]

(array([5, 6]), array([11, 12]))

In [23]:
np.zeros((3,3,4)),np.empty((3,3,4))

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 array([[[4.77644210e-310, 0.00000000e+000, 4.95268267e+223,
          7.23786621e+159],
         [3.02907763e-152, 1.39806872e-152, 5.98129759e-154,
          2.52303223e-258],
         [4.47593804e-091, 1.81644122e+223, 2.64519876e+185,
          2.21002231e+214]],
 
        [[1.96930981e+243, 2.64521684e+185, 7.36496487e+271,
          1.17567369e+214],
         [3.17095813e+180, 7.47727343e+247, 1.67432290e+243,
          4.88725514e+199],
         [1.46923002e+195, 2.44048419e-152, 6.20203970e+223,
          5.46653043e+241]],
 
        [[3.28095935e-085, 2.23209619e+271, 2.46598535e-154,
          4.47593816e-091],
         [6.01346953e-154, 2.17235227e-153, 1.69201561e+190,
          7.49744161e+247],
         [3.42702532e-062, 2.4

In [24]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [26]:
np.arange

TypeError: Cannot interpret '3' as a data type